### ISSUE TITLE
Surge multiplier not in response

### ISSUE THREAD

**Issue by moon47usaco** [filpia/uber_cool#1]
['surge_multiplier'] does not seem to be provided in the response any more as of v1.2 

Any chance you can help me get this working again?

I would love to recreate what you have done here for my area.

**Comment by filpia** [comment]
Hi,

Could you share some screenshots of what you're seeing that suggests the 'surge_multiplier' value is no longer included in the return object from the API? Or if there's some notes that Uber put out regarding changes to their API, that would work too. Admittedly, I haven't revised this project in a while but upon opening the 'Ping Uber API' notebook in the repo I can run the first cell and not get any errors about 'surge_multiplier' not being found.

**Comment by moon47usaco** [comment]
Thanks,

I get this when trying to print the results of get_surge().

IE: `print(get_surge(client,34.018666, -118.494126))`

Those are lat,lng in my area but I get same results with your cords.

`  File "/Volumes/...mydir.../Uber - Lyft/Python/Testing/Ping Uber API.py", line 37, in get_surge
    return response.json['prices'][0]['surge_multiplier']
KeyError: 'surge_multiplier'
[Finished in 3.5s with exit code 1]
[shell_cmd: python -u "/Volumes/...mydir.../Uber - Lyft/Python/Testing/Ping Uber API.py"]
[dir: /Volumes/...mydir.../Uber - Lyft/Python/Testing]
[path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin]`

Also looking at the complete results of response.json['prices'] I get a response similar to the one on the api doc page http://ubr.to/2FPudLW and 'surge_multiplier' is not there even if I know from other sources that there is surge in the coords I tested last night.

I also found this but I did not really understand it or how to implement:
https://stackoverflow.com/questions/46402129/uber-api-get-estimates-price-response-surge-multiplier-disappeared

**Comment by filpia** [comment]
In the V1.2 API doc page you link to, it looks like 'surge_multiplier' is still a valid value in the returned dictionary since it's defined at the bottom of the page though its presence may be subject to the product/surge being active, as explained towards the top of the file...

> When surge is active for a particular product, its surge_multiplier will be greater than 1, but the price estimate already factors in this multiplier.
> 

I'll try to recreate your issue using your coordinates and by making sure I hit the V1.2 endpoint and not V1 any longer.

**Comment by moon47usaco** [comment]
Ya, thats why I am a bit confused. I tested it with coordinates that I was certain were experiencing surge at the time. I also tried your original coordinates with the same result.

Looking at the "Results" section in the v1 and v1.2 show what I am experiencing. v1.2 results in the docs there is no "surge_multiplier" but there is on the v1 doc.

Thank for looking in to it, much appreciated =]

**Comment by filpia** [comment]
Pull the latest code from the repo. Note the comments I've added to the top of the README file. In short, it doesn't look like surge_multiplier will reliably be a part of the response as of V1.2 of estimates/price as Uber as shifted to an upfront pricing standard. We can still measure multiplicative changes in the price **after** we've collected enough rates to be able to determine a baseline price. 

While revising the Ping Uber API notebook I've rearranged some code for clarity. Note that you should now use get_ride_estimate() and pull_surge_v1_2() to get prices. Further, you might want to edit the 
`end_latitude_ and `end_longitude_ variables. Though you explicitly pass the start latitude and longitudes to the get_ride_estimate() function, end_latitude_ and end_longitude_ will assume a common endpoint for all your quoted rides. I would change these from the defaults I've set to reflect a realistic ride from the starting points you're using. Right now, they represent midtown Manhattan.

Good luck!

**Comment by moon47usaco** [comment]
This is what I was afraid of. Apparently there is still a way to get surge_multiplier from a "POST /v1.2/requests/estimate" but this requires using the sandbox to avoid requesting a real ride through the system. I will let you know when I find a solution for accessing real surge_multiplier for a given lat,lng.

Thanks for digging in to the I appreciate it.
